---
name: edges-daily

'on':
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SHEETS_EXPORT_URL: ${{ secrets.SHEETS_EXPORT_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  - name: Fetch latest odds CSV (optional)
    if: env.SHEETS_EXPORT_URL != ''
    run: |
      mkdir -p storage/imports
      curl -L "$SHEETS_EXPORT_URL" -o storage/imports/odds_snapshot.csv

  - name: Poll The Odds API once (NFL only)
    if: env.ODDS_API_KEYS != ''
    env:
      ODDS_API_KEYS: ${{ secrets.ODDS_API_KEYS }}
      ODDS_REGION: us
      ODDS_MARKETS: player_props
      ODDS_BOOKMAKERS: draftkings,fanduel,betmgm
    run: python jobs/poll_odds.py --once --sport nfl --markets player_props --region us

      - name: Build defense ratings (open data)
        run: python jobs/build_defense_ratings.py

      - name: Import odds CSV -> SQLite
        run: python jobs/import_odds_from_csv.py

      - name: Compute edges
        run: python jobs/compute_edges.py

      - name: Smoke test (season present end-to-end)
        run: python tests/smoke_season.py

      - name: Upload exports (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: edges-exports
          path: |
            storage/exports/edges_latest.csv
            storage/exports/edges_latest.parquet
          if-no-files-found: warn
