name: edges-daily

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -r requirements.txt
      - run: python jobs/build_defense_ratings.py
      # If keeping Google Sheets as source of truth:
      # - run: curl -L "$SHEETS_EXPORT_URL" -o storage/imports/odds_snapshot.csv
      - run: python jobs/import_odds_from_csv.py
      - run: python jobs/compute_edges.py
    env:
      ODDS_API_KEYS: ${{ secrets.ODDS_API_KEYS }}
      # SHEETS_EXPORT_URL: ${{ secrets.SHEETS_EXPORT_URL }}
